apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EAPEStagingPolicy
metadata:
    name: eape-staging-policy-constraint
spec:
    match:
        kinds:
            - apiGroups:
                - ""
              kinds:
                - Pod
        labelSelector:
            environment: staging
    parameters:
        maxFileSize: 50MB
        scanningMode: warn
